IMPORT INTO RF.TRAIN FROM LOCAL CSV FILE '<path to train.csv>' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'CRLF' 
COLUMN SEPARATOR = ',' 
COLUMN DELIMITER = '"'
SKIP = 1
REJECT LIMIT 0;

IMPORT INTO RF.TEST FROM LOCAL CSV FILE '<path to test.csv>' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'CRLF' 
COLUMN SEPARATOR = ';' 
COLUMN DELIMITER = '"' 
SKIP = 1
REJECT LIMIT 0;

select * from rf.test;
commit;